"""
jogadores.py - catalogo editavel dos jogadores do site.

Edite este arquivo para adicionar fotos, alterar jogadores existentes ou
cadastrar novos jogadores. O backend le esta lista ao iniciar e atualiza
a tabela de jogadores sem apagar figurinhas que os usuarios ja possuem.

Campos de cada jogador:
- name: nome exibido na carta.
- team_name: selecao/time do jogador.
- position: "Goleiro", "Zagueiro", "Meio-Campo" ou "Atacante".
- rating: forca de 1 a 5.
- foto: caminho da imagem em assets/players/. O site mostra em 184x255.

Para renomear ou trocar a selecao de um jogador ja salvo no banco, adicione
original_name e, se necessario, original_team_name no item editado.
"""

POSITIONS = ("Goleiro", "Zagueiro", "Meio-Campo", "Atacante")

JOGADORES = [
    # Base
    {"name": 'Matt Turner', "team_name": 'Base', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Alistair Johnston', "team_name": 'Base', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Walker Zimmerman', "team_name": 'Base', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Milos Degenek', "team_name": 'Base', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Yuto Nagatomo', "team_name": 'Base', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Kellyn Acosta', "team_name": 'Base', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Jackson Irvine', "team_name": 'Base', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Hwang In-beom', "team_name": 'Base', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Daichi Kamada', "team_name": 'Base', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Boulaye Dia', "team_name": 'Base', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Cho Gue-sung', "team_name": 'Base', "position": 'Atacante', "rating": 1, "foto": ''},

    # Brasil
    {"name": 'Alisson', "team_name": 'Brasil', "position": 'Goleiro', "rating": 5, "foto": ''},
    {"name": 'Marquinhos', "team_name": 'Brasil', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Casemiro', "team_name": 'Brasil', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Neymar', "team_name": 'Brasil', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Vinicius Jr', "team_name": 'Brasil', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Thiago Silva', "team_name": 'Brasil', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Éder Militão', "team_name": 'Brasil', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Lucas Paquetá', "team_name": 'Brasil', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Raphinha', "team_name": 'Brasil', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Gabriel Jesus', "team_name": 'Brasil', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Richarlison', "team_name": 'Brasil', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Brasil Goleiro 2', "team_name": 'Brasil', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Brasil Goleiro 3', "team_name": 'Brasil', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Brasil Zagueiro 4', "team_name": 'Brasil', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Brasil Zagueiro 5', "team_name": 'Brasil', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Brasil Zagueiro 6', "team_name": 'Brasil', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Brasil Zagueiro 7', "team_name": 'Brasil', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Brasil Meio-Campo 3', "team_name": 'Brasil', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Brasil Meio-Campo 4', "team_name": 'Brasil', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Brasil Meio-Campo 5', "team_name": 'Brasil', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Brasil Meio-Campo 6', "team_name": 'Brasil', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Brasil Meio-Campo 7', "team_name": 'Brasil', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Brasil Atacante 6', "team_name": 'Brasil', "position": 'Atacante', "rating": 4, "foto": ''},

    # França
    {"name": 'Mike Maignan', "team_name": 'França', "position": 'Goleiro', "rating": 5, "foto": ''},
    {"name": 'William Saliba', "team_name": 'França', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Eduardo Camavinga', "team_name": 'França', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Antoine Griezmann', "team_name": 'França', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Kylian Mbappé', "team_name": 'França', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Hugo Lloris', "team_name": 'França', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Jules Koundé', "team_name": 'França', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Dayot Upamecano', "team_name": 'França', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Aurélien Tchouaméni', "team_name": 'França', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Olivier Giroud', "team_name": 'França', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Ousmane Dembélé', "team_name": 'França', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'França Goleiro 3', "team_name": 'França', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'França Zagueiro 4', "team_name": 'França', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'França Zagueiro 5', "team_name": 'França', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'França Zagueiro 6', "team_name": 'França', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'França Zagueiro 7', "team_name": 'França', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'França Meio-Campo 3', "team_name": 'França', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'França Meio-Campo 4', "team_name": 'França', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'França Meio-Campo 5', "team_name": 'França', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'França Meio-Campo 6', "team_name": 'França', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'França Meio-Campo 7', "team_name": 'França', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'França Atacante 5', "team_name": 'França', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'França Atacante 6', "team_name": 'França', "position": 'Atacante', "rating": 4, "foto": ''},

    # Argentina
    {"name": 'Emiliano Martínez', "team_name": 'Argentina', "position": 'Goleiro', "rating": 5, "foto": ''},
    {"name": 'Cristian Romero', "team_name": 'Argentina', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Rodrigo De Paul', "team_name": 'Argentina', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Lautaro Martínez', "team_name": 'Argentina', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Lionel Messi', "team_name": 'Argentina', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Nicolás Otamendi', "team_name": 'Argentina', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Nahuel Molina', "team_name": 'Argentina', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Enzo Fernández', "team_name": 'Argentina', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Ángel Di María', "team_name": 'Argentina', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Julián Álvarez', "team_name": 'Argentina', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Paulo Dybala', "team_name": 'Argentina', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Argentina Goleiro 2', "team_name": 'Argentina', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Argentina Goleiro 3', "team_name": 'Argentina', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Argentina Zagueiro 4', "team_name": 'Argentina', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Argentina Zagueiro 5', "team_name": 'Argentina', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Argentina Zagueiro 6', "team_name": 'Argentina', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Argentina Zagueiro 7', "team_name": 'Argentina', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Argentina Meio-Campo 3', "team_name": 'Argentina', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Argentina Meio-Campo 4', "team_name": 'Argentina', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Argentina Meio-Campo 5', "team_name": 'Argentina', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Argentina Meio-Campo 6', "team_name": 'Argentina', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Argentina Meio-Campo 7', "team_name": 'Argentina', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Argentina Atacante 6', "team_name": 'Argentina', "position": 'Atacante', "rating": 4, "foto": ''},

    # Inglaterra
    {"name": 'Jordan Pickford', "team_name": 'Inglaterra', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'John Stones', "team_name": 'Inglaterra', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Jude Bellingham', "team_name": 'Inglaterra', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Phil Foden', "team_name": 'Inglaterra', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Harry Kane', "team_name": 'Inglaterra', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Kyle Walker', "team_name": 'Inglaterra', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Harry Maguire', "team_name": 'Inglaterra', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Declan Rice', "team_name": 'Inglaterra', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Bukayo Saka', "team_name": 'Inglaterra', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Marcus Rashford', "team_name": 'Inglaterra', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Raheem Sterling', "team_name": 'Inglaterra', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Goleiro 2', "team_name": 'Inglaterra', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Goleiro 3', "team_name": 'Inglaterra', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Zagueiro 4', "team_name": 'Inglaterra', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Zagueiro 5', "team_name": 'Inglaterra', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Zagueiro 6', "team_name": 'Inglaterra', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Zagueiro 7', "team_name": 'Inglaterra', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Meio-Campo 3', "team_name": 'Inglaterra', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Meio-Campo 4', "team_name": 'Inglaterra', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Meio-Campo 5', "team_name": 'Inglaterra', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Meio-Campo 6', "team_name": 'Inglaterra', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Meio-Campo 7', "team_name": 'Inglaterra', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Inglaterra Atacante 6', "team_name": 'Inglaterra', "position": 'Atacante', "rating": 4, "foto": ''},

    # Espanha
    {"name": 'Unai Simón', "team_name": 'Espanha', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Dani Carvajal', "team_name": 'Espanha', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Rodri', "team_name": 'Espanha', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Pedri', "team_name": 'Espanha', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Lamine Yamal', "team_name": 'Espanha', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Aymeric Laporte', "team_name": 'Espanha', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Jordi Alba', "team_name": 'Espanha', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Sergio Busquets', "team_name": 'Espanha', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Gavi', "team_name": 'Espanha', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Álvaro Morata', "team_name": 'Espanha', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Nico Williams', "team_name": 'Espanha', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Espanha Goleiro 2', "team_name": 'Espanha', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Espanha Goleiro 3', "team_name": 'Espanha', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Espanha Zagueiro 4', "team_name": 'Espanha', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Espanha Zagueiro 5', "team_name": 'Espanha', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Espanha Zagueiro 6', "team_name": 'Espanha', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Espanha Zagueiro 7', "team_name": 'Espanha', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Espanha Meio-Campo 5', "team_name": 'Espanha', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Espanha Meio-Campo 6', "team_name": 'Espanha', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Espanha Meio-Campo 7', "team_name": 'Espanha', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Espanha Atacante 4', "team_name": 'Espanha', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Espanha Atacante 5', "team_name": 'Espanha', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Espanha Atacante 6', "team_name": 'Espanha', "position": 'Atacante', "rating": 4, "foto": ''},

    # Alemanha
    {"name": 'Manuel Neuer', "team_name": 'Alemanha', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Antonio Rüdiger', "team_name": 'Alemanha', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Jamal Musiala', "team_name": 'Alemanha', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Florian Wirtz', "team_name": 'Alemanha', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Kai Havertz', "team_name": 'Alemanha', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Joshua Kimmich', "team_name": 'Alemanha', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'İlkay Gündoğan', "team_name": 'Alemanha', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Thomas Müller', "team_name": 'Alemanha', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Leroy Sané', "team_name": 'Alemanha', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Serge Gnabry', "team_name": 'Alemanha', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Niclas Füllkrug', "team_name": 'Alemanha', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Alemanha Goleiro 2', "team_name": 'Alemanha', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Alemanha Goleiro 3', "team_name": 'Alemanha', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Alemanha Zagueiro 2', "team_name": 'Alemanha', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Alemanha Zagueiro 3', "team_name": 'Alemanha', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Alemanha Zagueiro 4', "team_name": 'Alemanha', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Alemanha Zagueiro 5', "team_name": 'Alemanha', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Alemanha Zagueiro 6', "team_name": 'Alemanha', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Alemanha Zagueiro 7', "team_name": 'Alemanha', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Alemanha Meio-Campo 5', "team_name": 'Alemanha', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Alemanha Meio-Campo 6', "team_name": 'Alemanha', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Alemanha Meio-Campo 7', "team_name": 'Alemanha', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Alemanha Atacante 6', "team_name": 'Alemanha', "position": 'Atacante', "rating": 3, "foto": ''},

    # Portugal
    {"name": 'Diogo Costa', "team_name": 'Portugal', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Rúben Dias', "team_name": 'Portugal', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Bruno Fernandes', "team_name": 'Portugal', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Rafael Leão', "team_name": 'Portugal', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Cristiano Ronaldo', "team_name": 'Portugal', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Pepe', "team_name": 'Portugal', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'João Cancelo', "team_name": 'Portugal', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Bernardo Silva', "team_name": 'Portugal', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'João Félix', "team_name": 'Portugal', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Gonçalo Ramos', "team_name": 'Portugal', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Diogo Jota', "team_name": 'Portugal', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Portugal Goleiro 2', "team_name": 'Portugal', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Portugal Goleiro 3', "team_name": 'Portugal', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Portugal Zagueiro 4', "team_name": 'Portugal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Portugal Zagueiro 5', "team_name": 'Portugal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Portugal Zagueiro 6', "team_name": 'Portugal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Portugal Zagueiro 7', "team_name": 'Portugal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Portugal Meio-Campo 3', "team_name": 'Portugal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Portugal Meio-Campo 4', "team_name": 'Portugal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Portugal Meio-Campo 5', "team_name": 'Portugal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Portugal Meio-Campo 6', "team_name": 'Portugal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Portugal Meio-Campo 7', "team_name": 'Portugal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Portugal Atacante 6', "team_name": 'Portugal', "position": 'Atacante', "rating": 3, "foto": ''},

    # Países Baixos
    {"name": 'Bart Verbruggen', "team_name": 'Países Baixos', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Virgil van Dijk', "team_name": 'Países Baixos', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Frenkie de Jong', "team_name": 'Países Baixos', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Cody Gakpo', "team_name": 'Países Baixos', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Memphis Depay', "team_name": 'Países Baixos', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Países Baixos Goleiro 2', "team_name": 'Países Baixos', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Goleiro 3', "team_name": 'Países Baixos', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Zagueiro 2', "team_name": 'Países Baixos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Zagueiro 3', "team_name": 'Países Baixos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Zagueiro 4', "team_name": 'Países Baixos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Zagueiro 5', "team_name": 'Países Baixos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Zagueiro 6', "team_name": 'Países Baixos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Zagueiro 7', "team_name": 'Países Baixos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Meio-Campo 2', "team_name": 'Países Baixos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Meio-Campo 3', "team_name": 'Países Baixos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Meio-Campo 4', "team_name": 'Países Baixos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Meio-Campo 5', "team_name": 'Países Baixos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Meio-Campo 6', "team_name": 'Países Baixos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Meio-Campo 7', "team_name": 'Países Baixos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Atacante 3', "team_name": 'Países Baixos', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Atacante 4', "team_name": 'Países Baixos', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Atacante 5', "team_name": 'Países Baixos', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Países Baixos Atacante 6', "team_name": 'Países Baixos', "position": 'Atacante', "rating": 3, "foto": ''},

    # Bélgica
    {"name": 'Thibaut Courtois', "team_name": 'Bélgica', "position": 'Goleiro', "rating": 5, "foto": ''},
    {"name": 'Wout Faes', "team_name": 'Bélgica', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Kevin De Bruyne', "team_name": 'Bélgica', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Jérémy Doku', "team_name": 'Bélgica', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Romelu Lukaku', "team_name": 'Bélgica', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Bélgica Goleiro 2', "team_name": 'Bélgica', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Bélgica Goleiro 3', "team_name": 'Bélgica', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Bélgica Zagueiro 2', "team_name": 'Bélgica', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Bélgica Zagueiro 3', "team_name": 'Bélgica', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Bélgica Zagueiro 4', "team_name": 'Bélgica', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Bélgica Zagueiro 5', "team_name": 'Bélgica', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Bélgica Zagueiro 6', "team_name": 'Bélgica', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Bélgica Zagueiro 7', "team_name": 'Bélgica', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Bélgica Meio-Campo 2', "team_name": 'Bélgica', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Bélgica Meio-Campo 3', "team_name": 'Bélgica', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Bélgica Meio-Campo 4', "team_name": 'Bélgica', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Bélgica Meio-Campo 5', "team_name": 'Bélgica', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Bélgica Meio-Campo 6', "team_name": 'Bélgica', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Bélgica Meio-Campo 7', "team_name": 'Bélgica', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Bélgica Atacante 3', "team_name": 'Bélgica', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Bélgica Atacante 4', "team_name": 'Bélgica', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Bélgica Atacante 5', "team_name": 'Bélgica', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Bélgica Atacante 6', "team_name": 'Bélgica', "position": 'Atacante', "rating": 3, "foto": ''},

    # Croácia
    {"name": 'Dominik Livaković', "team_name": 'Croácia', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Joško Gvardiol', "team_name": 'Croácia', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Luka Modrić', "team_name": 'Croácia', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Mateo Kovačić', "team_name": 'Croácia', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Andrej Kramarić', "team_name": 'Croácia', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Dejan Lovren', "team_name": 'Croácia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Marcelo Brozović', "team_name": 'Croácia', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Ivan Perišić', "team_name": 'Croácia', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Mario Pašalić', "team_name": 'Croácia', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Bruno Petković', "team_name": 'Croácia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Mislav Oršić', "team_name": 'Croácia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Croácia Goleiro 2', "team_name": 'Croácia', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Croácia Goleiro 3', "team_name": 'Croácia', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Croácia Zagueiro 3', "team_name": 'Croácia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Croácia Zagueiro 4', "team_name": 'Croácia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Croácia Zagueiro 5', "team_name": 'Croácia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Croácia Zagueiro 6', "team_name": 'Croácia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Croácia Zagueiro 7', "team_name": 'Croácia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Croácia Meio-Campo 5', "team_name": 'Croácia', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Croácia Meio-Campo 6', "team_name": 'Croácia', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Croácia Meio-Campo 7', "team_name": 'Croácia', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Croácia Atacante 5', "team_name": 'Croácia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Croácia Atacante 6', "team_name": 'Croácia', "position": 'Atacante', "rating": 3, "foto": ''},

    # Uruguai
    {"name": 'Sergio Rochet', "team_name": 'Uruguai', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Ronald Araújo', "team_name": 'Uruguai', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Federico Valverde', "team_name": 'Uruguai', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Darwin Núñez', "team_name": 'Uruguai', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Luis Suárez', "team_name": 'Uruguai', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Fernando Muslera', "team_name": 'Uruguai', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'José María Giménez', "team_name": 'Uruguai', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Rodrigo Bentancur', "team_name": 'Uruguai', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Giorgian de Arrascaeta', "team_name": 'Uruguai', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Edinson Cavani', "team_name": 'Uruguai', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Facundo Pellistri', "team_name": 'Uruguai', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Uruguai Goleiro 3', "team_name": 'Uruguai', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Uruguai Zagueiro 3', "team_name": 'Uruguai', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Uruguai Zagueiro 4', "team_name": 'Uruguai', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Uruguai Zagueiro 5', "team_name": 'Uruguai', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Uruguai Zagueiro 6', "team_name": 'Uruguai', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Uruguai Zagueiro 7', "team_name": 'Uruguai', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Uruguai Meio-Campo 4', "team_name": 'Uruguai', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Uruguai Meio-Campo 5', "team_name": 'Uruguai', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Uruguai Meio-Campo 6', "team_name": 'Uruguai', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Uruguai Meio-Campo 7', "team_name": 'Uruguai', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Uruguai Atacante 5', "team_name": 'Uruguai', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Uruguai Atacante 6', "team_name": 'Uruguai', "position": 'Atacante', "rating": 3, "foto": ''},

    # Itália
    {"name": 'Gianluigi Donnarumma', "team_name": 'Itália', "position": 'Goleiro', "rating": 5, "foto": ''},
    {"name": 'Alessandro Bastoni', "team_name": 'Itália', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Nicolò Barella', "team_name": 'Itália', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Federico Chiesa', "team_name": 'Itália', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Gianluca Scamacca', "team_name": 'Itália', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Itália Goleiro 2', "team_name": 'Itália', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Itália Goleiro 3', "team_name": 'Itália', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Itália Zagueiro 2', "team_name": 'Itália', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Itália Zagueiro 3', "team_name": 'Itália', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Itália Zagueiro 4', "team_name": 'Itália', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Itália Zagueiro 5', "team_name": 'Itália', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Itália Zagueiro 6', "team_name": 'Itália', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Itália Zagueiro 7', "team_name": 'Itália', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Itália Meio-Campo 2', "team_name": 'Itália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Itália Meio-Campo 3', "team_name": 'Itália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Itália Meio-Campo 4', "team_name": 'Itália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Itália Meio-Campo 5', "team_name": 'Itália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Itália Meio-Campo 6', "team_name": 'Itália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Itália Meio-Campo 7', "team_name": 'Itália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Itália Atacante 3', "team_name": 'Itália', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Itália Atacante 4', "team_name": 'Itália', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Itália Atacante 5', "team_name": 'Itália', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Itália Atacante 6', "team_name": 'Itália', "position": 'Atacante', "rating": 3, "foto": ''},

    # EUA
    {"name": 'Matt Turner', "team_name": 'EUA', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Antonee Robinson', "team_name": 'EUA', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Weston McKennie', "team_name": 'EUA', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Christian Pulisic', "team_name": 'EUA', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Folarin Balogun', "team_name": 'EUA', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'EUA Goleiro 2', "team_name": 'EUA', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'EUA Goleiro 3', "team_name": 'EUA', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'EUA Zagueiro 2', "team_name": 'EUA', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'EUA Zagueiro 3', "team_name": 'EUA', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'EUA Zagueiro 4', "team_name": 'EUA', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'EUA Zagueiro 5', "team_name": 'EUA', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'EUA Zagueiro 6', "team_name": 'EUA', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'EUA Zagueiro 7', "team_name": 'EUA', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'EUA Meio-Campo 2', "team_name": 'EUA', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'EUA Meio-Campo 3', "team_name": 'EUA', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'EUA Meio-Campo 4', "team_name": 'EUA', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'EUA Meio-Campo 5', "team_name": 'EUA', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'EUA Meio-Campo 6', "team_name": 'EUA', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'EUA Meio-Campo 7', "team_name": 'EUA', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'EUA Atacante 3', "team_name": 'EUA', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'EUA Atacante 4', "team_name": 'EUA', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'EUA Atacante 5', "team_name": 'EUA', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'EUA Atacante 6', "team_name": 'EUA', "position": 'Atacante', "rating": 3, "foto": ''},

    # Marrocos
    {"name": 'Yassine Bounou', "team_name": 'Marrocos', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Achraf Hakimi', "team_name": 'Marrocos', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Sofyan Amrabat', "team_name": 'Marrocos', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Hakim Ziyech', "team_name": 'Marrocos', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Youssef En-Nesyri', "team_name": 'Marrocos', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Romain Saïss', "team_name": 'Marrocos', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Nayef Aguerd', "team_name": 'Marrocos', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Azzedine Ounahi', "team_name": 'Marrocos', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Selim Amallah', "team_name": 'Marrocos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Sofiane Boufal', "team_name": 'Marrocos', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Abderrazak Hamdallah', "team_name": 'Marrocos', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Marrocos Goleiro 2', "team_name": 'Marrocos', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Marrocos Goleiro 3', "team_name": 'Marrocos', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Marrocos Zagueiro 4', "team_name": 'Marrocos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Marrocos Zagueiro 5', "team_name": 'Marrocos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Marrocos Zagueiro 6', "team_name": 'Marrocos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Marrocos Zagueiro 7', "team_name": 'Marrocos', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Marrocos Meio-Campo 4', "team_name": 'Marrocos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Marrocos Meio-Campo 5', "team_name": 'Marrocos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Marrocos Meio-Campo 6', "team_name": 'Marrocos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Marrocos Meio-Campo 7', "team_name": 'Marrocos', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Marrocos Atacante 5', "team_name": 'Marrocos', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Marrocos Atacante 6', "team_name": 'Marrocos', "position": 'Atacante', "rating": 3, "foto": ''},

    # Japão
    {"name": 'Zion Suzuki', "team_name": 'Japão', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Takehiro Tomiyasu', "team_name": 'Japão', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Wataru Endo', "team_name": 'Japão', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Takefusa Kubo', "team_name": 'Japão', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Kaoru Mitoma', "team_name": 'Japão', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Japão Goleiro 2', "team_name": 'Japão', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Japão Goleiro 3', "team_name": 'Japão', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Japão Zagueiro 2', "team_name": 'Japão', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Japão Zagueiro 3', "team_name": 'Japão', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Japão Zagueiro 4', "team_name": 'Japão', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Japão Zagueiro 5', "team_name": 'Japão', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Japão Zagueiro 6', "team_name": 'Japão', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Japão Zagueiro 7', "team_name": 'Japão', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Japão Meio-Campo 2', "team_name": 'Japão', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Japão Meio-Campo 3', "team_name": 'Japão', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Japão Meio-Campo 4', "team_name": 'Japão', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Japão Meio-Campo 5', "team_name": 'Japão', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Japão Meio-Campo 6', "team_name": 'Japão', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Japão Meio-Campo 7', "team_name": 'Japão', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Japão Atacante 3', "team_name": 'Japão', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Japão Atacante 4', "team_name": 'Japão', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Japão Atacante 5', "team_name": 'Japão', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Japão Atacante 6', "team_name": 'Japão', "position": 'Atacante', "rating": 3, "foto": ''},

    # México
    {"name": 'Guillermo Ochoa', "team_name": 'México', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Edson Álvarez', "team_name": 'México', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Luis Chávez', "team_name": 'México', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Hirving Lozano', "team_name": 'México', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Santiago Giménez', "team_name": 'México', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'México Goleiro 2', "team_name": 'México', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'México Goleiro 3', "team_name": 'México', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'México Zagueiro 2', "team_name": 'México', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'México Zagueiro 3', "team_name": 'México', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'México Zagueiro 4', "team_name": 'México', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'México Zagueiro 5', "team_name": 'México', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'México Zagueiro 6', "team_name": 'México', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'México Zagueiro 7', "team_name": 'México', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'México Meio-Campo 2', "team_name": 'México', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'México Meio-Campo 3', "team_name": 'México', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'México Meio-Campo 4', "team_name": 'México', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'México Meio-Campo 5', "team_name": 'México', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'México Meio-Campo 6', "team_name": 'México', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'México Meio-Campo 7', "team_name": 'México', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'México Atacante 3', "team_name": 'México', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'México Atacante 4', "team_name": 'México', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'México Atacante 5', "team_name": 'México', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'México Atacante 6', "team_name": 'México', "position": 'Atacante', "rating": 3, "foto": ''},

    # Senegal
    {"name": 'Édouard Mendy', "team_name": 'Senegal', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Kalidou Koulibaly', "team_name": 'Senegal', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Idrissa Gueye', "team_name": 'Senegal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Ismaïla Sarr', "team_name": 'Senegal', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Sadio Mané', "team_name": 'Senegal', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Senegal Goleiro 2', "team_name": 'Senegal', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Senegal Goleiro 3', "team_name": 'Senegal', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Senegal Zagueiro 2', "team_name": 'Senegal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Senegal Zagueiro 3', "team_name": 'Senegal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Senegal Zagueiro 4', "team_name": 'Senegal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Senegal Zagueiro 5', "team_name": 'Senegal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Senegal Zagueiro 6', "team_name": 'Senegal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Senegal Zagueiro 7', "team_name": 'Senegal', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Senegal Meio-Campo 2', "team_name": 'Senegal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Senegal Meio-Campo 3', "team_name": 'Senegal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Senegal Meio-Campo 4', "team_name": 'Senegal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Senegal Meio-Campo 5', "team_name": 'Senegal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Senegal Meio-Campo 6', "team_name": 'Senegal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Senegal Meio-Campo 7', "team_name": 'Senegal', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Senegal Atacante 3', "team_name": 'Senegal', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Senegal Atacante 4', "team_name": 'Senegal', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Senegal Atacante 5', "team_name": 'Senegal', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Senegal Atacante 6', "team_name": 'Senegal', "position": 'Atacante', "rating": 3, "foto": ''},

    # Dinamarca
    {"name": 'Kasper Schmeichel', "team_name": 'Dinamarca', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Andreas Christensen', "team_name": 'Dinamarca', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Joachim Andersen', "team_name": 'Dinamarca', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Pierre-Emile Højbjerg', "team_name": 'Dinamarca', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Christian Eriksen', "team_name": 'Dinamarca', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Mikkel Damsgaard', "team_name": 'Dinamarca', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Rasmus Højlund', "team_name": 'Dinamarca', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Yussuf Poulsen', "team_name": 'Dinamarca', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Goleiro 2', "team_name": 'Dinamarca', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Goleiro 3', "team_name": 'Dinamarca', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Zagueiro 3', "team_name": 'Dinamarca', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Zagueiro 4', "team_name": 'Dinamarca', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Zagueiro 5', "team_name": 'Dinamarca', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Zagueiro 6', "team_name": 'Dinamarca', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Zagueiro 7', "team_name": 'Dinamarca', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Meio-Campo 4', "team_name": 'Dinamarca', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Meio-Campo 5', "team_name": 'Dinamarca', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Meio-Campo 6', "team_name": 'Dinamarca', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Meio-Campo 7', "team_name": 'Dinamarca', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Atacante 3', "team_name": 'Dinamarca', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Atacante 4', "team_name": 'Dinamarca', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Atacante 5', "team_name": 'Dinamarca', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Dinamarca Atacante 6', "team_name": 'Dinamarca', "position": 'Atacante', "rating": 3, "foto": ''},

    # Austrália
    {"name": 'Mathew Ryan', "team_name": 'Austrália', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Harry Souttar', "team_name": 'Austrália', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Aziz Behich', "team_name": 'Austrália', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Jackson Irvine', "team_name": 'Austrália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Aaron Mooy', "team_name": 'Austrália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Ajdin Hrustic', "team_name": 'Austrália', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Mathew Leckie', "team_name": 'Austrália', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Craig Goodwin', "team_name": 'Austrália', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Mitchell Duke', "team_name": 'Austrália', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Austrália Goleiro 2', "team_name": 'Austrália', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Austrália Goleiro 3', "team_name": 'Austrália', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Austrália Zagueiro 3', "team_name": 'Austrália', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Austrália Zagueiro 4', "team_name": 'Austrália', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Austrália Zagueiro 5', "team_name": 'Austrália', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Austrália Zagueiro 6', "team_name": 'Austrália', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Austrália Zagueiro 7', "team_name": 'Austrália', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Austrália Meio-Campo 4', "team_name": 'Austrália', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Austrália Meio-Campo 5', "team_name": 'Austrália', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Austrália Meio-Campo 6', "team_name": 'Austrália', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Austrália Meio-Campo 7', "team_name": 'Austrália', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Austrália Atacante 4', "team_name": 'Austrália', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Austrália Atacante 5', "team_name": 'Austrália', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Austrália Atacante 6', "team_name": 'Austrália', "position": 'Atacante', "rating": 2, "foto": ''},

    # Suíça
    {"name": 'Yann Sommer', "team_name": 'Suíça', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Manuel Akanji', "team_name": 'Suíça', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Ricardo Rodríguez', "team_name": 'Suíça', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Granit Xhaka', "team_name": 'Suíça', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Remo Freuler', "team_name": 'Suíça', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Xherdan Shaqiri', "team_name": 'Suíça', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Breel Embolo', "team_name": 'Suíça', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Noah Okafor', "team_name": 'Suíça', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Suíça Goleiro 2', "team_name": 'Suíça', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Suíça Goleiro 3', "team_name": 'Suíça', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Suíça Zagueiro 3', "team_name": 'Suíça', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Suíça Zagueiro 4', "team_name": 'Suíça', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Suíça Zagueiro 5', "team_name": 'Suíça', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Suíça Zagueiro 6', "team_name": 'Suíça', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Suíça Zagueiro 7', "team_name": 'Suíça', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Suíça Meio-Campo 3', "team_name": 'Suíça', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Suíça Meio-Campo 4', "team_name": 'Suíça', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Suíça Meio-Campo 5', "team_name": 'Suíça', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Suíça Meio-Campo 6', "team_name": 'Suíça', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Suíça Meio-Campo 7', "team_name": 'Suíça', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Suíça Atacante 4', "team_name": 'Suíça', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Suíça Atacante 5', "team_name": 'Suíça', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Suíça Atacante 6', "team_name": 'Suíça', "position": 'Atacante', "rating": 2, "foto": ''},

    # Coreia do Sul
    {"name": 'Kim Seung-gyu', "team_name": 'Coreia do Sul', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Kim Min-jae', "team_name": 'Coreia do Sul', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Kim Young-gwon', "team_name": 'Coreia do Sul', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Hwang In-beom', "team_name": 'Coreia do Sul', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Lee Kang-in', "team_name": 'Coreia do Sul', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Son Heung-min', "team_name": 'Coreia do Sul', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Hwang Hee-chan', "team_name": 'Coreia do Sul', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Cho Gue-sung', "team_name": 'Coreia do Sul', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Coreia do Sul Goleiro 2', "team_name": 'Coreia do Sul', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Goleiro 3', "team_name": 'Coreia do Sul', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Zagueiro 3', "team_name": 'Coreia do Sul', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Zagueiro 4', "team_name": 'Coreia do Sul', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Zagueiro 5', "team_name": 'Coreia do Sul', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Zagueiro 6', "team_name": 'Coreia do Sul', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Zagueiro 7', "team_name": 'Coreia do Sul', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Meio-Campo 3', "team_name": 'Coreia do Sul', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Meio-Campo 4', "team_name": 'Coreia do Sul', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Meio-Campo 5', "team_name": 'Coreia do Sul', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Meio-Campo 6', "team_name": 'Coreia do Sul', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Meio-Campo 7', "team_name": 'Coreia do Sul', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Atacante 4', "team_name": 'Coreia do Sul', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Atacante 5', "team_name": 'Coreia do Sul', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Coreia do Sul Atacante 6', "team_name": 'Coreia do Sul', "position": 'Atacante', "rating": 2, "foto": ''},

    # Polônia
    {"name": 'Wojciech Szczęsny', "team_name": 'Polônia', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Jan Bednarek', "team_name": 'Polônia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Jakub Kiwior', "team_name": 'Polônia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Piotr Zieliński', "team_name": 'Polônia', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Grzegorz Krychowiak', "team_name": 'Polônia', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Robert Lewandowski', "team_name": 'Polônia', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Arkadiusz Milik', "team_name": 'Polônia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Karol Świderski', "team_name": 'Polônia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Polônia Goleiro 2', "team_name": 'Polônia', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Polônia Goleiro 3', "team_name": 'Polônia', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Polônia Zagueiro 3', "team_name": 'Polônia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Polônia Zagueiro 4', "team_name": 'Polônia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Polônia Zagueiro 5', "team_name": 'Polônia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Polônia Zagueiro 6', "team_name": 'Polônia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Polônia Zagueiro 7', "team_name": 'Polônia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Polônia Meio-Campo 3', "team_name": 'Polônia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Polônia Meio-Campo 4', "team_name": 'Polônia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Polônia Meio-Campo 5', "team_name": 'Polônia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Polônia Meio-Campo 6', "team_name": 'Polônia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Polônia Meio-Campo 7', "team_name": 'Polônia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Polônia Atacante 4', "team_name": 'Polônia', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Polônia Atacante 5', "team_name": 'Polônia', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Polônia Atacante 6', "team_name": 'Polônia', "position": 'Atacante', "rating": 2, "foto": ''},

    # Colômbia
    {"name": 'Camilo Vargas', "team_name": 'Colômbia', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Davinson Sánchez', "team_name": 'Colômbia', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Yerry Mina', "team_name": 'Colômbia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Jefferson Lerma', "team_name": 'Colômbia', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'James Rodríguez', "team_name": 'Colômbia', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Luis Díaz', "team_name": 'Colômbia', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Jhon Arias', "team_name": 'Colômbia', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Rafael Borré', "team_name": 'Colômbia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Colômbia Goleiro 2', "team_name": 'Colômbia', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Colômbia Goleiro 3', "team_name": 'Colômbia', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Colômbia Zagueiro 3', "team_name": 'Colômbia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Colômbia Zagueiro 4', "team_name": 'Colômbia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Colômbia Zagueiro 5', "team_name": 'Colômbia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Colômbia Zagueiro 6', "team_name": 'Colômbia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Colômbia Zagueiro 7', "team_name": 'Colômbia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Colômbia Meio-Campo 3', "team_name": 'Colômbia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Colômbia Meio-Campo 4', "team_name": 'Colômbia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Colômbia Meio-Campo 5', "team_name": 'Colômbia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Colômbia Meio-Campo 6', "team_name": 'Colômbia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Colômbia Meio-Campo 7', "team_name": 'Colômbia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Colômbia Atacante 4', "team_name": 'Colômbia', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Colômbia Atacante 5', "team_name": 'Colômbia', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Colômbia Atacante 6', "team_name": 'Colômbia', "position": 'Atacante', "rating": 2, "foto": ''},

    # Nigéria
    {"name": 'Stanley Nwabali', "team_name": 'Nigéria', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'William Troost-Ekong', "team_name": 'Nigéria', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Calvin Bassey', "team_name": 'Nigéria', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Wilfred Ndidi', "team_name": 'Nigéria', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Alex Iwobi', "team_name": 'Nigéria', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Victor Osimhen', "team_name": 'Nigéria', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Ademola Lookman', "team_name": 'Nigéria', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Samuel Chukwueze', "team_name": 'Nigéria', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Nigéria Goleiro 2', "team_name": 'Nigéria', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Nigéria Goleiro 3', "team_name": 'Nigéria', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Nigéria Zagueiro 3', "team_name": 'Nigéria', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Nigéria Zagueiro 4', "team_name": 'Nigéria', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Nigéria Zagueiro 5', "team_name": 'Nigéria', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Nigéria Zagueiro 6', "team_name": 'Nigéria', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Nigéria Zagueiro 7', "team_name": 'Nigéria', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Nigéria Meio-Campo 3', "team_name": 'Nigéria', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Nigéria Meio-Campo 4', "team_name": 'Nigéria', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Nigéria Meio-Campo 5', "team_name": 'Nigéria', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Nigéria Meio-Campo 6', "team_name": 'Nigéria', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Nigéria Meio-Campo 7', "team_name": 'Nigéria', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Nigéria Atacante 4', "team_name": 'Nigéria', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Nigéria Atacante 5', "team_name": 'Nigéria', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Nigéria Atacante 6', "team_name": 'Nigéria', "position": 'Atacante', "rating": 2, "foto": ''},

    # Sérvia
    {"name": 'Predrag Rajković', "team_name": 'Sérvia', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Nikola Milenković', "team_name": 'Sérvia', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Strahinja Pavlović', "team_name": 'Sérvia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Sergej Milinković-Savić', "team_name": 'Sérvia', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Dušan Tadić', "team_name": 'Sérvia', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Dušan Vlahović', "team_name": 'Sérvia', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Aleksandar Mitrović', "team_name": 'Sérvia', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Filip Kostić', "team_name": 'Sérvia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Sérvia Goleiro 2', "team_name": 'Sérvia', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Sérvia Goleiro 3', "team_name": 'Sérvia', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Sérvia Zagueiro 3', "team_name": 'Sérvia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Sérvia Zagueiro 4', "team_name": 'Sérvia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Sérvia Zagueiro 5', "team_name": 'Sérvia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Sérvia Zagueiro 6', "team_name": 'Sérvia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Sérvia Zagueiro 7', "team_name": 'Sérvia', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Sérvia Meio-Campo 3', "team_name": 'Sérvia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Sérvia Meio-Campo 4', "team_name": 'Sérvia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Sérvia Meio-Campo 5', "team_name": 'Sérvia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Sérvia Meio-Campo 6', "team_name": 'Sérvia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Sérvia Meio-Campo 7', "team_name": 'Sérvia', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Sérvia Atacante 4', "team_name": 'Sérvia', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Sérvia Atacante 5', "team_name": 'Sérvia', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Sérvia Atacante 6', "team_name": 'Sérvia', "position": 'Atacante', "rating": 2, "foto": ''},

    # Irã
    {"name": 'Alireza Beiranvand', "team_name": 'Irã', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Morteza Pouraliganji', "team_name": 'Irã', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Majid Hosseini', "team_name": 'Irã', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Saeid Ezatolahi', "team_name": 'Irã', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Saman Ghoddos', "team_name": 'Irã', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Mehdi Taremi', "team_name": 'Irã', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Sardar Azmoun', "team_name": 'Irã', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Alireza Jahanbakhsh', "team_name": 'Irã', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Irã Goleiro 2', "team_name": 'Irã', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Irã Goleiro 3', "team_name": 'Irã', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Irã Zagueiro 3', "team_name": 'Irã', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Irã Zagueiro 4', "team_name": 'Irã', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Irã Zagueiro 5', "team_name": 'Irã', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Irã Zagueiro 6', "team_name": 'Irã', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Irã Zagueiro 7', "team_name": 'Irã', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Irã Meio-Campo 3', "team_name": 'Irã', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Irã Meio-Campo 4', "team_name": 'Irã', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Irã Meio-Campo 5', "team_name": 'Irã', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Irã Meio-Campo 6', "team_name": 'Irã', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Irã Meio-Campo 7', "team_name": 'Irã', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Irã Atacante 4', "team_name": 'Irã', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Irã Atacante 5', "team_name": 'Irã', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Irã Atacante 6', "team_name": 'Irã', "position": 'Atacante', "rating": 1, "foto": ''},

    # Equador
    {"name": 'Alexander Domínguez', "team_name": 'Equador', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Piero Hincapié', "team_name": 'Equador', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Pervis Estupiñán', "team_name": 'Equador', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Moisés Caicedo', "team_name": 'Equador', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'Carlos Gruezo', "team_name": 'Equador', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Enner Valencia', "team_name": 'Equador', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Gonzalo Plata', "team_name": 'Equador', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Kevin Rodríguez', "team_name": 'Equador', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Equador Goleiro 2', "team_name": 'Equador', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Equador Goleiro 3', "team_name": 'Equador', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Equador Zagueiro 3', "team_name": 'Equador', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Equador Zagueiro 4', "team_name": 'Equador', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Equador Zagueiro 5', "team_name": 'Equador', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Equador Zagueiro 6', "team_name": 'Equador', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Equador Zagueiro 7', "team_name": 'Equador', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Equador Meio-Campo 3', "team_name": 'Equador', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Equador Meio-Campo 4', "team_name": 'Equador', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Equador Meio-Campo 5', "team_name": 'Equador', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Equador Meio-Campo 6', "team_name": 'Equador', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Equador Meio-Campo 7', "team_name": 'Equador', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Equador Atacante 4', "team_name": 'Equador', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Equador Atacante 5', "team_name": 'Equador', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Equador Atacante 6', "team_name": 'Equador', "position": 'Atacante', "rating": 1, "foto": ''},

    # Canadá
    {"name": 'Milan Borjan', "team_name": 'Canadá', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Alphonso Davies', "team_name": 'Canadá', "position": 'Zagueiro', "rating": 5, "foto": ''},
    {"name": 'Alistair Johnston', "team_name": 'Canadá', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Stephen Eustáquio', "team_name": 'Canadá', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Ismaël Koné', "team_name": 'Canadá', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Jonathan David', "team_name": 'Canadá', "position": 'Atacante', "rating": 5, "foto": ''},
    {"name": 'Cyle Larin', "team_name": 'Canadá', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Tajon Buchanan', "team_name": 'Canadá', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Canadá Goleiro 2', "team_name": 'Canadá', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Canadá Goleiro 3', "team_name": 'Canadá', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Canadá Zagueiro 3', "team_name": 'Canadá', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Canadá Zagueiro 4', "team_name": 'Canadá', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Canadá Zagueiro 5', "team_name": 'Canadá', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Canadá Zagueiro 6', "team_name": 'Canadá', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Canadá Zagueiro 7', "team_name": 'Canadá', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Canadá Meio-Campo 3', "team_name": 'Canadá', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Canadá Meio-Campo 4', "team_name": 'Canadá', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Canadá Meio-Campo 5', "team_name": 'Canadá', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Canadá Meio-Campo 6', "team_name": 'Canadá', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Canadá Meio-Campo 7', "team_name": 'Canadá', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Canadá Atacante 4', "team_name": 'Canadá', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Canadá Atacante 5', "team_name": 'Canadá', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Canadá Atacante 6', "team_name": 'Canadá', "position": 'Atacante', "rating": 1, "foto": ''},

    # Gana
    {"name": 'Lawrence Ati-Zigi', "team_name": 'Gana', "position": 'Goleiro', "rating": 3, "foto": ''},
    {"name": 'Daniel Amartey', "team_name": 'Gana', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Mohammed Salisu', "team_name": 'Gana', "position": 'Zagueiro', "rating": 4, "foto": ''},
    {"name": 'Thomas Partey', "team_name": 'Gana', "position": 'Meio-Campo', "rating": 4, "foto": ''},
    {"name": 'Mohammed Kudus', "team_name": 'Gana', "position": 'Meio-Campo', "rating": 5, "foto": ''},
    {"name": 'André Ayew', "team_name": 'Gana', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Iñaki Williams', "team_name": 'Gana', "position": 'Atacante', "rating": 4, "foto": ''},
    {"name": 'Jordan Ayew', "team_name": 'Gana', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Gana Goleiro 2', "team_name": 'Gana', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Gana Goleiro 3', "team_name": 'Gana', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Gana Zagueiro 3', "team_name": 'Gana', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Gana Zagueiro 4', "team_name": 'Gana', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Gana Zagueiro 5', "team_name": 'Gana', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Gana Zagueiro 6', "team_name": 'Gana', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Gana Zagueiro 7', "team_name": 'Gana', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Gana Meio-Campo 3', "team_name": 'Gana', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Gana Meio-Campo 4', "team_name": 'Gana', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Gana Meio-Campo 5', "team_name": 'Gana', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Gana Meio-Campo 6', "team_name": 'Gana', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Gana Meio-Campo 7', "team_name": 'Gana', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Gana Atacante 4', "team_name": 'Gana', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Gana Atacante 5', "team_name": 'Gana', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Gana Atacante 6', "team_name": 'Gana', "position": 'Atacante', "rating": 1, "foto": ''},

    # Costa Rica
    {"name": 'Keylor Navas', "team_name": 'Costa Rica', "position": 'Goleiro', "rating": 4, "foto": ''},
    {"name": 'Francisco Calvo', "team_name": 'Costa Rica', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Óscar Duarte', "team_name": 'Costa Rica', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Celso Borges', "team_name": 'Costa Rica', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Bryan Ruiz', "team_name": 'Costa Rica', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Joel Campbell', "team_name": 'Costa Rica', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Anthony Contreras', "team_name": 'Costa Rica', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Costa Rica Goleiro 2', "team_name": 'Costa Rica', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Goleiro 3', "team_name": 'Costa Rica', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Zagueiro 3', "team_name": 'Costa Rica', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Zagueiro 4', "team_name": 'Costa Rica', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Zagueiro 5', "team_name": 'Costa Rica', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Zagueiro 6', "team_name": 'Costa Rica', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Zagueiro 7', "team_name": 'Costa Rica', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Meio-Campo 3', "team_name": 'Costa Rica', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Meio-Campo 4', "team_name": 'Costa Rica', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Meio-Campo 5', "team_name": 'Costa Rica', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Meio-Campo 6', "team_name": 'Costa Rica', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Meio-Campo 7', "team_name": 'Costa Rica', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Atacante 3', "team_name": 'Costa Rica', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Atacante 4', "team_name": 'Costa Rica', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Atacante 5', "team_name": 'Costa Rica', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Costa Rica Atacante 6', "team_name": 'Costa Rica', "position": 'Atacante', "rating": 1, "foto": ''},

    # Tunísia
    {"name": 'Aymen Dahmen', "team_name": 'Tunísia', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Dylan Bronn', "team_name": 'Tunísia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Montassar Talbi', "team_name": 'Tunísia', "position": 'Zagueiro', "rating": 3, "foto": ''},
    {"name": 'Ellyes Skhiri', "team_name": 'Tunísia', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Aïssa Laïdouni', "team_name": 'Tunísia', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Wahbi Khazri', "team_name": 'Tunísia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Youssef Msakni', "team_name": 'Tunísia', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Tunísia Goleiro 2', "team_name": 'Tunísia', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Tunísia Goleiro 3', "team_name": 'Tunísia', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Tunísia Zagueiro 3', "team_name": 'Tunísia', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Tunísia Zagueiro 4', "team_name": 'Tunísia', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Tunísia Zagueiro 5', "team_name": 'Tunísia', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Tunísia Zagueiro 6', "team_name": 'Tunísia', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Tunísia Zagueiro 7', "team_name": 'Tunísia', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Tunísia Meio-Campo 3', "team_name": 'Tunísia', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Tunísia Meio-Campo 4', "team_name": 'Tunísia', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Tunísia Meio-Campo 5', "team_name": 'Tunísia', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Tunísia Meio-Campo 6', "team_name": 'Tunísia', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Tunísia Meio-Campo 7', "team_name": 'Tunísia', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Tunísia Atacante 3', "team_name": 'Tunísia', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Tunísia Atacante 4', "team_name": 'Tunísia', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Tunísia Atacante 5', "team_name": 'Tunísia', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Tunísia Atacante 6', "team_name": 'Tunísia', "position": 'Atacante', "rating": 1, "foto": ''},

    # Arábia Saudita
    {"name": 'Mohammed Al-Owais', "team_name": 'Arábia Saudita', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Yasser Al-Shahrani', "team_name": 'Arábia Saudita', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Ali Al-Bulaihi', "team_name": 'Arábia Saudita', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Mohamed Kanno', "team_name": 'Arábia Saudita', "position": 'Meio-Campo', "rating": 3, "foto": ''},
    {"name": 'Salem Al-Dawsari', "team_name": 'Arábia Saudita', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Firas Al-Buraikan', "team_name": 'Arábia Saudita', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Saleh Al-Shehri', "team_name": 'Arábia Saudita', "position": 'Atacante', "rating": 2, "foto": ''},
    {"name": 'Arábia Saudita Goleiro 2', "team_name": 'Arábia Saudita', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Goleiro 3', "team_name": 'Arábia Saudita', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Zagueiro 3', "team_name": 'Arábia Saudita', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Zagueiro 4', "team_name": 'Arábia Saudita', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Zagueiro 5', "team_name": 'Arábia Saudita', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Zagueiro 6', "team_name": 'Arábia Saudita', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Zagueiro 7', "team_name": 'Arábia Saudita', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Meio-Campo 2', "team_name": 'Arábia Saudita', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Meio-Campo 3', "team_name": 'Arábia Saudita', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Meio-Campo 4', "team_name": 'Arábia Saudita', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Meio-Campo 5', "team_name": 'Arábia Saudita', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Meio-Campo 6', "team_name": 'Arábia Saudita', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Meio-Campo 7', "team_name": 'Arábia Saudita', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Atacante 4', "team_name": 'Arábia Saudita', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Atacante 5', "team_name": 'Arábia Saudita', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Arábia Saudita Atacante 6', "team_name": 'Arábia Saudita', "position": 'Atacante', "rating": 1, "foto": ''},

    # Catar
    {"name": 'Saad Al Sheeb', "team_name": 'Catar', "position": 'Goleiro', "rating": 2, "foto": ''},
    {"name": 'Pedro Miguel', "team_name": 'Catar', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Boualem Khoukhi', "team_name": 'Catar', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Abdelkarim Hassan', "team_name": 'Catar', "position": 'Zagueiro', "rating": 2, "foto": ''},
    {"name": 'Hassan Al-Haydos', "team_name": 'Catar', "position": 'Meio-Campo', "rating": 2, "foto": ''},
    {"name": 'Akram Afif', "team_name": 'Catar', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Almoez Ali', "team_name": 'Catar', "position": 'Atacante', "rating": 3, "foto": ''},
    {"name": 'Catar Goleiro 2', "team_name": 'Catar', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Catar Goleiro 3', "team_name": 'Catar', "position": 'Goleiro', "rating": 1, "foto": ''},
    {"name": 'Catar Zagueiro 4', "team_name": 'Catar', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Catar Zagueiro 5', "team_name": 'Catar', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Catar Zagueiro 6', "team_name": 'Catar', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Catar Zagueiro 7', "team_name": 'Catar', "position": 'Zagueiro', "rating": 1, "foto": ''},
    {"name": 'Catar Meio-Campo 2', "team_name": 'Catar', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Catar Meio-Campo 3', "team_name": 'Catar', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Catar Meio-Campo 4', "team_name": 'Catar', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Catar Meio-Campo 5', "team_name": 'Catar', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Catar Meio-Campo 6', "team_name": 'Catar', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Catar Meio-Campo 7', "team_name": 'Catar', "position": 'Meio-Campo', "rating": 1, "foto": ''},
    {"name": 'Catar Atacante 3', "team_name": 'Catar', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Catar Atacante 4', "team_name": 'Catar', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Catar Atacante 5', "team_name": 'Catar', "position": 'Atacante', "rating": 1, "foto": ''},
    {"name": 'Catar Atacante 6', "team_name": 'Catar', "position": 'Atacante', "rating": 1, "foto": ''},

]


def _normalize_player(data: dict) -> dict:
    name = str(data.get("name", "")).strip()
    team_name = str(data.get("team_name", "")).strip()
    position = str(data.get("position", "")).strip()

    if not name or not team_name:
        raise ValueError("Jogador precisa de name e team_name")
    if position not in POSITIONS:
        raise ValueError(f"{name}: position precisa ser uma destas: {', '.join(POSITIONS)}")

    try:
        rating = int(data.get("rating", 1))
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name}: rating precisa ser um numero de 1 a 5") from exc

    normalized = {
        "name": name,
        "team_name": team_name,
        "position": position,
        "rating": max(1, min(5, rating)),
    }

    photo_url = data.get("photo_url", data.get("foto", data.get("imagem", None)))
    normalized["photo_url"] = str(photo_url).strip() or None if photo_url is not None else None

    original_name = str(data.get("original_name", "")).strip()
    original_team_name = str(data.get("original_team_name", "")).strip()
    if original_name:
        normalized["_match_name"] = original_name
    if original_team_name:
        normalized["_match_team_name"] = original_team_name

    return normalized


def get_initial_players() -> list[dict]:
    """Retorna uma copia validada do catalogo de jogadores."""
    return [_normalize_player(player) for player in JOGADORES]
